"""fix trigger column

Revision ID: 0fba9852eaaf
Revises: 73d576ebe60b
Create Date: 2026-04-22 12:25:37.792770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fba9852eaaf'
down_revision: Union[str, Sequence[str], None] = '73d576ebe60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('expected_status', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('max_latency_ms', sa.Integer(), nullable=True),
    sa.Column('failure_threshold', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.Enum('healthy', 'degraded', 'unhealthy', name='servicestatus'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_current_status'), 'services', ['current_status'], unique=False)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('health_check_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_check_logs_checked_at'), 'health_check_logs', ['checked_at'], unique=False)
    op.create_index(op.f('ix_health_check_logs_id'), 'health_check_logs', ['id'], unique=False)
    op.create_index(op.f('ix_health_check_logs_service_id'), 'health_check_logs', ['service_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Enum('active', 'resolved', name='state'), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('alert_attempts', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_service_id'), 'incidents', ['service_id'], unique=False)
    op.create_index(op.f('ix_incidents_state'), 'incidents', ['state'], unique=False)
    op.create_table('incident_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('report_content', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.Enum('manual', 'on_resolve', 'on_open', name='reporttrigger'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_incident_id'), 'incident_reports', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_reports_incident_id'), table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_index(op.f('ix_incidents_state'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_service_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_health_check_logs_service_id'), table_name='health_check_logs')
    op.drop_index(op.f('ix_health_check_logs_id'), table_name='health_check_logs')
    op.drop_index(op.f('ix_health_check_logs_checked_at'), table_name='health_check_logs')
    op.drop_table('health_check_logs')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_services_current_status'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
